### ISSUE TITLE
Check performance Observations(1469076)/Datastream

### ISSUE THREAD

**Issue by bertt** [Geodan/gost#101]
http://gost.geodan.nl/v1.0/Observations(1469076)/Datastream seems a bit slow, 4-5 seconds

**Comment by bertt** [comment]
generated sql statement (on http://localhost:8080/v1.0/Observations(5)/Datastream): 

SELECT datastream.id AS A_datastream_id, datastream.name AS A_datastream_name, datastream.description AS A_datastream_description, datastream.unitofmeasurement AS A_datastream_unitofmeasurement, datastream.observationtype AS A_datastream_observationtype, public.ST_AsGeoJSON(datastream.observedarea) AS A_datastream_observedarea, datastream.phenomenontime AS A_datastream_phenomenontime, datastream.resulttime AS A_datastream_resulttime FROM v1.datastream INNER JOIN LATERAL (SELECT observation.id AS observation_id FROM v1.observation WHERE observation.stream_id = datastream.id ) AS observation on true  WHERE datastream.id IN (SELECT datastream.id FROM v1.datastream INNER JOIN LATERAL (SELECT observation.id AS observation_id FROM v1.observation WHERE observation.stream_id = datastream.id ) AS observation on true  WHERE observation.observation_id = 5 ORDER BY datastream.id DESC LIMIT 20 OFFSET 0) ORDER BY datastream.id DESC

**Comment by bertt** [comment]
but why do I get 5 results instead of 1?

**Comment by bertt** [comment]
proposal:

```
SELECT datastream.id AS A_datastream_id, 
datastream.name AS A_datastream_name, 
datastream.description AS A_datastream_description, 
datastream.unitofmeasurement AS A_datastream_unitofmeasurement, 
datastream.observationtype AS A_datastream_observationtype, 
public.ST_AsGeoJSON(datastream.observedarea) AS A_datastream_observedarea, 
datastream.phenomenontime AS A_datastream_phenomenontime, 
datastream.resulttime AS A_datastream_resulttime 
FROM v1.datastream, v1.observation
WHERE datastream.id=v1.observation.stream_id and v1.observation.id=5
ORDER BY datastream.id DESC
```
gives 1 result

**Comment by bertt** [comment]
new query (with today's commit):

```
SELECT 
datastream.datastream_id AS datastream_id, 
datastream.datastream_name AS datastream_name, 
datastream.datastream_description AS datastream_description, 
datastream.datastream_unitofmeasurement AS datastream_unitofmeasurement, 
datastream.datastream_observationtype AS datastream_observationtype, 
datastream.datastream_observedarea AS datastream_observedarea, 
datastream.datastream_phenomenontime AS datastream_phenomenontime, 
datastream.datastream_resulttime AS datastream_resulttime 
FROM 
( 
    SELECT datastream.thing_id AS datastream_thing_id, 
    datastream.observedproperty_id AS datastream_observedproperty_id, 
    datastream.sensor_id AS datastream_sensor_id, 
    datastream.id AS datastream_id, 
    datastream.name AS datastream_name, 
    datastream.description AS datastream_description, 
    datastream.unitofmeasurement AS datastream_unitofmeasurement, 
    datastream.observationtype AS datastream_observationtype, 
    public.ST_AsGeoJSON(datastream.observedarea) AS datastream_observedarea, 
    datastream.phenomenontime AS datastream_phenomenontime, 
    datastream.resulttime AS datastream_resulttime 
    FROM v1.datastream 
    ORDER BY datastream.id DESC
) AS datastream 
INNER JOIN LATERAL (
    SELECT observation.id AS observation_id FROM v1.observation 
    WHERE observation.stream_id = datastream.datastream_id 
    AND observation.id = 1469076
    ) AS observation on true  
LIMIT 20 
OFFSET 0
```

**Comment by bertt** [comment]
gives 1 result, and faster...

Query could be simplified to above proposal?

**Comment by tebben** [comment]
Simplified proposal will not work when more filters and joins are needed,
 for example: http://localhost:8080/v1.0/Observations(5)/Datastream?$expand=Observations($select=id,result;$top=5;$filter=result gt 10),Thing/Locations,Thing/HistoricalLocations

Did a simple performance test and looks like the current query from the QueryBuilder performs the same.

**Comment by bertt** [comment]
issue is that querys will get quite lengthy and unreadable with all properties duplicated in the 'select' and the 'from' part. 
Will be interesting to see if it's possible to simplify above query to:

```
SELECT 
	public.ST_AsGeoJSON(datastream.observedarea) AS datastream_observedarea, 
	datastream.id AS A_datastream_id, 
	datastream.name AS A_datastream_name, 
	datastream.description AS A_datastream_description, 
	datastream.unitofmeasurement AS A_datastream_unitofmeasurement, 
	datastream.observationtype AS A_datastream_observationtype, 
	datastream.observedarea AS A_datastream_observedarea, 
	datastream.phenomenontime AS A_datastream_phenomenontime, 
	datastream.resulttime AS A_datastream_resulttime 
FROM datastream 
INNER JOIN LATERAL (
	SELECT observation.id AS observation_id 
	FROM v1.observation 
	WHERE observation.stream_id = datastream.id AND 
	observation.id = 5
) 
AS observation on true  LIMIT 20 OFFSET 0
```
With this construction, why is not possible to add OData query's?
