### ISSUE TITLE
Using alpine (again)

### ISSUE THREAD

**Issue by bertt** [Geodan/gost#103]
Shall have another Alpine attempt?

Proposal change base images: 

- gost-db:  mdillon/postgis:9.6 (221MB)  -> mdillon/postgis:9.6-alpine (33MB)

Change: https://github.com/gost/gost-db/blob/master/Dockerfile#L1

- gost: golang:latest (266 MB) -> golang:1.8-alpine (78MB)

Change: https://github.com/Geodan/gost/blob/master/Dockerfile#L1

- dashboard:  nginx:latest (44MB) -> nginx:alpine (7MB)

Change: https://github.com/gost/dashboard/blob/master/Dockerfile#L1

Todo: Test if they work, if so, change for 0.6 release (gost tag latest)

Todo: Find Alpine base images for Mosquitto and Node-RED

**Comment by bertt** [comment]
mdillon/postgis:9.6-alpine seems to work well

**Comment by tebben** [comment]
Can you check the performance by inserting a few times thing with location, datastream, sensor, observedProperty and observation? Last time i tried alpine for gost and gost-db I had some major performance issues, taking around 1.5 seconds for the post instead of +/- 60ms.

{
    "name": "lantern",
    "description": "camping lantern",
    "properties": {
        "property1": "it’s waterproof",
        "property2": "it glows in the dark",
        "property3": "it repels insects"
    },
    "Locations": [{
        "name": "bla",
        "description": "my backyard",
        "encodingType": "application/vnd.geo+json",
        "location": {
            "type": "Point",
            "coordinates": [-117.123,
            54.123]
        }
    }],
    "Datastreams": [{
        "name": "DS1",
        "unitOfMeasurement": {
            "name": "Celsius",
            "symbol": "C",
            "definition": "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#Celsius"
        },
        "description": "Temperature measurement",
        "observationType": "http://www.opengis.net/def/observationType/OGC-OM/2.0/OM_Measurement",
        "ObservedProperty": {
            "name": "Temperature",
            "definition": "http://www.qudt.org/qudt/owl/1.0.0/quantity/Instances.html#Temperature",
            "description": "Temperature of the camping site"
        },
        "Sensor": {
            "name": "This is a name",
            "description": "SensorUp Tempomatic 2000",
            "encodingType": "application/pdf",
            "metadata": "Calibration date:  Jan 1, 2014"
        },
        "Observations": [
                {
                  "phenomenonTime": "2015-04-13T00:00:00Z",
                  "resultTime" : "2015-04-13T00:00:05Z",
                  "result" : 38
                }
            ]
    }]
}

**Comment by tebben** [comment]
Maybe you can also take a look at this blogpost for creating a tiny image: https://www.iron.io/an-easier-way-to-create-tiny-golang-docker-images/

**Comment by bertt** [comment]
Testcase:

```
$ ab -n 10 -p testinsert.txt -T "appliction/json" http://localhost/v1.0/Things
```
[testinsert.txt](https://github.com/Geodan/gost/files/1118869/testinsert.txt)

**Comment by bertt** [comment]
first results:

```
no alpine used: not measured
with mdillon/postgis:9.6-alpine: 8.8 ms/request
with mdillon/postgis:9.6-alpine and golang:1.8-alpine: 4.8 ms/request
with mdillon/postgis:9.6-alpine and golang:1.8-alpine and nginx:alpine: 2.8 ms/request
```

so its actually getting faster according to these results.

**Comment by bertt** [comment]
Alpine changes in Docker images:

geodan/gost: https://github.com/Geodan/gost/commit/b9af3c3aa3ab7eb9231105b4b2afc9d8c16b7156

geodan/gost-dashboard: 
https://github.com/gost/dashboard/commit/691a8181a5fe88ca9964d60f39326eb30d020f53

geodan/gost-db: https://github.com/gost/gost-db/commit/0611b3667328eb6451792e439cb34856ec682cac

**Comment by bertt** [comment]
shall push images @tebben ?

**Comment by tebben** [comment]
Almost done adding some more filter functions, let's create 0.5 images after that and release?

**Comment by tebben** [comment]
New images seem to be slower when inserting observations with 60 threads using JMeter, let's keep the non alpine versions for now and have a look at it later (release v1.0 ?)

**Comment by bertt** [comment]
ok, will be interesting to see which part is slower (dashboard/gost/db), can you attach Jmeter script?

**Comment by tebben** [comment]
[POST Observation.zip](https://github.com/Geodan/gost/files/1122337/POST.Observation.zip)
![alpine](https://user-images.githubusercontent.com/6178776/27833806-976f337a-60d4-11e7-9bae-aa6559c1fc1c.jpg)

**Comment by tebben** [comment]
closing for now
