### ISSUE TITLE
Minute function gives no results

### ISSUE THREAD

**Issue by bertt** [Geodan/gost#108]
sample:

```
$ curl http://localhost:8080/v1.0/Observations?$filter=minute(phenomenonTime) eq 35
```

actual: no results
expected: return observation with "phenomenonTime": "2017-07-04T08:35:19.2508453Z" 

same with hour and second functions

**Comment by tebben** [comment]
Works on my machine

**Comment by bertt** [comment]
installed on PWD (running 4 hours from now)+ created observation (http://pwd10-0-84-3-8080.host1.labs.play-with-docker.com:8080/v1.0/Observations), expect return observation when running:

```
$ curl http://pwd10-0-84-3-8080.host1.labs.play-with-docker.com:8080/v1.0/Observations?$filter=minute(phenomenonTime) eq 37
```

**Comment by bertt** [comment]
relevant sql: 

select * FROM v1.observation 
WHERE EXTRACT(MINUTE FROM to_timestamp(observation.data ->> 'phenomenonTime','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')) = 5

observation.data: "{"result": 5, "phenomenonTime": "2017-07-04T12:05:57.6045285Z"}"

gives no results

**Comment by bertt** [comment]
select EXTRACT(MINUTE FROM to_timestamp(observation.data ->> 'phenomenonTime','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))  FROM v1.observation 

gives 35

**Comment by bertt** [comment]
select to_timestamp(observation.data ->> 'phenomenonTime','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') FROM v1.observation

gives: "2017-07-04 12:35:07.317704+00"

**Comment by bertt** [comment]
so the workaround is adding 30 minutes???

works: http://localhost:8080/v1.0/Observations?$filter=minute(phenomenonTime) eq 35

**Comment by bertt** [comment]
diving into the sql... for 2 observations:

select to_timestamp(observation.data ->> 'phenomenonTime','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') FROM v1.observation

"{"result": 5, "phenomenonTime": "2017-07-04T12:05:57.6045285Z"}";"2017-07-04 12:35:07.317704+00"
"{"result": 5, "phenomenonTime": "2017-07-04T12:27:52.0859507Z"}";"2017-07-04 12:42:11.507+00"

**Comment by bertt** [comment]
reducing further:

SELECT to_timestamp('2017-07-04T12:05:57.6045285Z', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"');

gives: "2017-07-04 12:35:07.317704+00"

**Comment by bertt** [comment]
changing MS to US:

SELECT to_timestamp('2017-07-04T12:05:57.6045285Z', 'YYYY-MM-DD"T"HH24:MI:SS.US"Z"');

gives: "2017-07-04 12:06:03.045285+00"

fix: change MS to US

**Comment by bertt** [comment]
plus reducing decimals to 6:

SELECT to_timestamp('2017-07-04T12:05:57.604528Z', 'YYYY-MM-DD"T"HH24:MI:SS.US"Z"');

gives: "2017-07-04 12:05:57.604528+00"

**Comment by bertt** [comment]
so whats the fix? reducing microseconds number of decimals (to 6) in all datetime fields?

**Comment by tebben** [comment]
when passing ms for resultTime and phenomenonTime they were already set to 3 digits. Problem was the auto assigned time produced by the server, this time is also now set to use 3 digits for the milliseconds: https://github.com/Geodan/gost/commit/bb9ec408d5fce9a111ed5e3766af63cade498115

**Comment by bertt** [comment]
hour, minute functions now work, some problems left with second function (noting returns)
