### ISSUE TITLE
Date function error

### ISSUE THREAD

**Issue by bertt** [Geodan/gost#113]
sample:

```
$ curl http://localhost:8080/v1.0/Observations?$filter=date(phenomenonTime) eq 0
```

reponse:
```
{
   "error": {
      "status": "Internal Server Error",
      "code": 500,
      "message": [
         "Error executing query pq: operator does not exist: date = integer"
      ]
   }
}

from spec: "The date function returns the date part of the DateTimeOffset parameter value, evaluated in the time zone of the DateTimeOffset parameter value."

**Comment by tebben** [comment]
What are you trying to do, according to ODATA specs:
5.1.1.6.1 date

The date function has the following signature:
Edm.Date date(Edm.DateTimeOffset)

The date function returns the date part of the DateTimeOffset parameter value, evaluated in the time zone of the DateTimeOffset parameter value.

This is working: http://localhost:8080/v1.0/Observations?$filter=date(phenomenonTime) eq date('2015-03-10')

**Comment by bertt** [comment]
okay, having a working example is the goal for now.

**Comment by bertt** [comment]
last sample works
