### ISSUE TITLE
st_overlaps return null

### ISSUE THREAD

**Issue by bertt** [Geodan/gost#115]
sample:

```
$ curl http://localhost:8080/v1.0/Locations?$filter=st_overlaps(location, geography'POLYGON ((-180 -90, -180 90, 180 90, 180 -90, -180 -90))')
```

With location:
```
{
    "name": "TestPoly",
    "description": "TestPoly",
    "encodingType": "application/vnd.geo+json",
    "location": {
        "type": "Polygon",
        "coordinates": [[[100,50], [10,9], [23,4],[100,50]], [[30,20], [10,4], [4,22], [30,20]]]
    }
}
```

reponse:

```
{
   "value": null
}
```

**Comment by tebben** [comment]
Seems to work on my machine

request
-----------------------------------------------------
http://localhost:8080/v1.0/Locations?$filter=st_overlaps(location,%20geography%27POLYGON%20((-180%20-90,%20-180%2090,%20180%2090,%20180%20-90,%20-180%20-90))%27)

response
-----------------------------------------------------
{
   "@iot.count": 1,
   "value": [
      {
         "@iot.id": 356,
         "@iot.selfLink": "http://localhost:8080/v1.0/Locations(356)",
         "name": "bla",
         "description": "my backyard",
         "encodingType": "application/vnd.geo+json",
         "location": {
            "coordinates": [
               [
                  [
                     181,
                     0
                  ],
                  [
                     101,
                     0
                  ],
                  [
                     101,
                     1
                  ],
                  [
                     181,
                     1
                  ],
                  [
                     181,
                     0
                  ]
               ]
            ],
            "type": "Polygon"
         },
         "Things@iot.navigationLink": "http://localhost:8080/v1.0/Locations(356)/Things",
         "HistoricalLocations@iot.navigationLink": "http://localhost:8080/v1.0/Locations(356)/HistoricalLocations"
      }
   ]
}

**Comment by bertt** [comment]
works now, using your polygon
