### ISSUE TITLE
st_relate sample

### ISSUE THREAD

**Issue by bertt** [Geodan/gost#120]
whats a working filter url using st_relate? 

in spec's it's a bit cryptic:

```
$filter = st_relate(location, geography'POLYGON ((30 10, 10 20, 20 40, 40 40, 30 10))', 'T********')
```

**Comment by tebben** [comment]
ST_Relate — Returns true if this Geometry is spatially related to another geometry, by testing for intersections between the Interior, Boundary and Exterior of the two geometries as specified by the values in the **intersectionMatrixPattern**. 

st_relate(geom1, geom2, intersectionMatrixPattern)

Check https://en.wikipedia.org/wiki/DE-9IM for intersection matrix patterns such as T*F**FFF* (Equals) FF*FF**** (Disjoint) T*****FF* (Contains)

**Comment by bertt** [comment]
does it work?

**Comment by bertt** [comment]
did a run of https://github.com/opengeospatial/ets-sta10/pull/26 , all spatial requests are working except the relate function.

```
$ curl http://localhost:8080/v1.0/Locations?$filter=st_relate(geography'POLYGON((7.5 51.5, 7.5 53.5, 8.5 53.5, 8.5 51.5, 7.5 51.5))', location, 'T********')
```

actual response: 
```
{
   "value": null
}
```

expected response: 4 entities

**Comment by tebben** [comment]
After commit https://github.com/Geodan/gost/commit/e784d172f78900f022ac885b40fd397c6dd930aa the following requests are working: 

```
http://localhost:8080/v1.0/Locations?$filter=st_relate(location, geography'POLYGON ((30 10, 10 20, 20 40, 40 40, 30 10))', 'T*****FF*')
```
```
http://localhost:8080/v1.0/Locations?$filter=st_relate(geography'POLYGON((7.5 51.5, 7.5 53.5, 8.5 53.5, 8.5 51.5, 7.5 51.5))', location, 'T********')
```
Not tested with opengeospatial/ets-sta10#26 yet, still need to get it running on my ubuntu machine

**Comment by bertt** [comment]
<img width="681" alt="screen shot 2017-07-14 at 13 35 35" src="https://user-images.githubusercontent.com/538812/28210790-8066a4fc-6899-11e7-950e-ced061317c41.png">
👍
