### ISSUE TITLE
Conformance core test: GET request to nonexistent entity is 404

### ISSUE THREAD

**Issue by bertt** [Geodan/gost#14]
sample: http://gost.geodan.nl/v1.0/Things(9223372036854775807)
probably type of id field

**Comment by bertt** [comment]
panic on method thing.go/ProcessThings
	rows, err := db.Query(sql, args...)
sql: select id, description, properties from v1.thing where id = 9223372036854775807

**Comment by tebben** [comment]
fixed: https://github.com/Geodan/gost/commit/6351f95b2897018e38d636b697d1bebb84394c61
