### ISSUE TITLE
Conformance core test: Add support for requesting properties like v1.0/Things(2)/description

### ISSUE THREAD

**Issue by bertt** [Geodan/gost#16]
sample http://gost.geodan.nl/v1.0/Things(2)/description
requesting properties should be implemented

**Comment by bertt** [comment]
Definition: 9.2.4 Usage 4: address to a property of an entity

sample: http://example.org/v1.0/Observations(1)/resultTime
response:
{
"resultTime": "2010-12-23T10:20:00-07:00"
}

**Comment by tebben** [comment]
implemented
