### ISSUE TITLE
Conformance CUD test: fill response Location header after POST

### ISSUE THREAD

**Issue by bertt** [Geodan/gost#20]
Create an entity: "Upon successful completion, the response SHALL contain a HTTP location header that contains the selfLink of the created entity."

Sample header:
Location →  http://gost.geodan.nl/v1.0/Things(1)

**Comment by tebben** [comment]
fixed -> https://github.com/Geodan/gost/commit/9bf42092ddde587343585bdd8d1347f5801242bf
