### ISSUE TITLE
Conformance Crud Test: Post to Datastream should work

### ISSUE THREAD

**Issue by bertt** [Geodan/gost#26]
Request:
localhost:8080/v1.0/Datastreams
{
  "unitOfMeasurement": {
    "name": "Celsius",
    "symbol": "degC",
    "definition": "http://qudt.org/vocab/unit#DegreeCelsius"
  },
  "description": "test datastream.",
  "observationType": "http://www.opengis.net/def/observationType/OGC-OM/2.0/OM_Measurement",
  "Thing": { "@iot.id": 1 },
  "ObservedProperty":{ "@iot.id":1},
  "Sensor": { "@iot.id": 1 }
}

Response:
{
  "error": {
    "status": "Bad Request",
    "code": 400,
    "message": [
      "Thing does not exist"
    ]
  }
}

But http://localhost:8080/v1.0/Things(1) does exist

**Comment by bertt** [comment]
this works:
{
"unitOfMeasurement": {
"name": "Celsius",
"symbol": "degC",
"definition": "http://qudt.org/vocab/unit#DegreeCelsius"
},
"description": "test datastream.",
"observationType": "http://www.opengis.net/def/observationType/OGC-OM/2.0/OM_Measurement",
"Thing": { "@iot.id": "1" },
"ObservedProperty":{ "@iot.id":"1"},
"Sensor": { "@iot.id": "1" }
}

**Comment by tebben** [comment]
fixed
