### ISSUE TITLE
Conformance Crud tests: Patch and Put should be implemented

### ISSUE THREAD

**Issue by bertt** [Geodan/gost#27]
Implement HTTP Put and Patch on entities

**Comment by bertt** [comment]
Sample PUT: 
http://localhost:8080/v1.0/Things(1)
{"description":"This is a Updated Test Thing From TestNG"}

**Comment by bertt** [comment]
Sample PATCH:
http://localhost:8080/v1.0/Things(1)
{"description":"This is a PATCHED Test Thing From TestNG"}

**Comment by tebben** [comment]
fixed
