### ISSUE TITLE
Mosquitto crashes

### ISSUE THREAD

**Issue by bertt** [Geodan/gost#40]
Occasionally we see Mosquitto broker crashes on the server:

kern.log:May 26 09:36:25 gost kernel: [313113.955286] mosquitto[708]: segfault at e3a1 ip 00007fdafab66a0c sp 00007fff16bd2b50 error 4 in libwebsockets.so.7[7fdafab5e000+1f000]

**Comment by bertt** [comment]
something going wrong in libwebsockets.so

**Comment by changqian9** [comment]
I can repro this bug on my ubuntu 14.04 (mosquitto 1.4.8 + libwebsockets7), for over 2 times.

**Comment by bertt** [comment]
yes we run mosquitto version 1.4.8 on Ubuntu

**Comment by changqian9** [comment]
I've created an issue at https://github.com/eclipse/mosquitto/issues/227

**Comment by bertt** [comment]
ok thanks! whats the repro?

**Comment by changqian9** [comment]
I can not repeat this every time. I deployed the broker with websockets enabled, connected over websocket tunnel.. it worked fine at first, but after a few weeks mqtt exited and can not be started until I reboot the server.

**Comment by cordovapolymer** [comment]
Same issue! Mosquitto crashes every second day, I have to restart it manually.
`
kernel: [1006237.390667] mosquitto[25279]: segfault at 54 ip 00007f367c6bd6e4 sp 00007fff389dcd60 error 6 in libwebsockets.so.3.0.0[7f367c6b9000+10000]`

Most interesting thing that I run it on two ports: mqtt 1883  and websockets 8000, it stops listening on mqtt 1883 port but continues operation on websockets 8000. After a restart it fully recovers until the next crash.  

I'm running mosquitto on debian 8.5 jessie installed from the [official repository ](http://repo.mosquitto.org/debian/mosquitto-jessie.list). The issue happened both on 1.4.8 and 1.4.9, I've just updated it to 1.4.10, and will post a follow-up if the issue persists.

**Comment by bertt** [comment]
seems related to size of message? see https://github.com/eclipse/mosquitto/issues/253#issuecomment-249392985

**Comment by bertt** [comment]
we've seen no mosquitto crashes since using the docker image 'toke/mosquitto' on our server. Its reporting version 1.4.10. So closing for now.
