### ISSUE TITLE
Add secure gost service (https)

### ISSUE THREAD

**Issue by tomvantilburg** [Geodan/gost#43]
At the moment a secure service is missing. Most browsers don't accept data retrieval from non-secure servers when the original domain is secure (from https to http).

**Comment by tebben** [comment]
Added support for HTTPS in commit https://github.com/Geodan/gost/commit/729cac5a21d6e51e593f67940e7d6547a096d839

Enable trough config file
https: false // use https true/false
httpsCert: // file location of cert file
httpsKey: // file location of key file

Or use environment variables
gost_server_https
gost_server_https_key
gost_server_https_cert
