### ISSUE TITLE
add Datastream - PhenomenonTime and ResultTime support

### ISSUE THREAD

**Issue by bertt** [Geodan/gost#48]
add Datastream  - PhenomenonTime and ResultTime support

**Comment by bertt** [comment]
phenomenonTime: "The temporal interval of the phenomenon times of all observations belonging to this Datastream."
resultTime: "The temporal interval of the result times of all observations belonging to this Datastream."

both optional

**Comment by bertt** [comment]
Datatype: TM_Period (ISO 8601 Time Interval)

**Comment by bertt** [comment]
sample query: update v1.datastream set phenomenontime='[2014-03-01T13:00:00Z, 2015-05-11T15:30:00Z]' where id=29

**Comment by bertt** [comment]
Current status:
. Post Datastream + PhenomenonTime:  PhenomenonTime is stored in column Datastream.PhenomenonTime (type tstzrange)
. Post Datastream + ResultTime:  ResultTime is stored in column Datastream.ResultTime (type tstzrange)
. Get Datastream: PhenomenonTime is retrieved, but ResultTime not
. Patch: ?

Todo: Support Post Datastream.ResultTime, Get DataStream.ResultTime

**Comment by bertt** [comment]
added code for posting http Datastream.ResultTime

**Comment by bertt** [comment]
but the service is returning:
[\"2014-03-01 13:00:00+00\",\"2015-05-11 15:30:00+00\"]"

have to convert it to iso8601 period (2014-03-01T13:00:00Z/2015-05-11T15:30:00Z) somewhere

**Comment by bertt** [comment]
created library https://github.com/gost/now for all time related functions

**Comment by bertt** [comment]
http get datastream PhenomenonTime and ResultTime in Iso8601 format working https://github.com/Geodan/gost/commit/9424dd642622a2890b6157b8c2f28530af080ad3

**Comment by bertt** [comment]
http patch datastream.phenomenontime and resulttime fixed

**Comment by dschowta** [comment]
Hi Bertt, 

It looks like OGC standard has different formats for Phenomenontime of Datastream (2014-03-01T13:00:00Z) and Observation (2014-12-31T11:59:59.00+08:00). 
When I view the observations from the server, the phenomenontime is shown as (2017-08-03T17:56:32.372Z) even if I feed the server with time entry as (2017-08-03T17:56:32.372+00:00).  Which I feel is a problem. 

-Thanks
