### ISSUE TITLE
Add support for Observation properties resultQuality, validTime and parameters 

### ISSUE THREAD

**Issue by bertt** [Geodan/gost#52]
from the spec: 

resultQuality: "Describes the quality of the result."
DQ_Element -Zero-to-many

validTime: "The time period during which the result may be used."  
TM_Period (ISO 8601 Time Interval string)  
Zero-to-one

parameters "Key-value pairs showing the environmental conditions during measurement.    NamedValues in a JSON Array"  
Zero-to-one

**Comment by tebben** [comment]
Just works..
