### ISSUE TITLE
Return 400 when url casing is not correct

### ISSUE THREAD

**Issue by bertt** [Geodan/gost#54]
sample: http://gost.geodan.nl/v1.0/DataStreams(17)/Observations
actual response: All observations
expected response: 400 error

**Comment by bertt** [comment]
related: http://localhost:8080/v1.0/aap/Observations returns all observations

**Comment by tebben** [comment]
The service is now case insensitive, defined endpoints and incoming request are set to lowercase and tested against a list of available paths.  Unknown paths such as "aap" do not work anymore and gost will return 404 not found.

https://github.com/Geodan/gost/commit/0ee11a251f063ceb1bafdf0021036b7bef5815aa
