### ISSUE TITLE
third-party dashboard testing

### ISSUE THREAD

**Issue by tebben** [Geodan/gost#56]

**Comment by bertt** [comment]
we need to implement this method (at least):

Request: http://gost.geodan.nl/v1.0/Datastreams(52)?$expand=ObservedProperty&$select=unitOfMeasurement,ObservedProperty

Sample Response:
{
	"unitOfMeasurement": {
		"symbol": "°C",
		"name": "degree Celsius",
		"definition": "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#DegreeCelsius"
	},
	"ObservedProperty": {
		"@iot.id": 4200,
		"@iot.selfLink": "http://gost.geodan.nl/v1.0/ObservedProperties(4200)",
		"description": "s_t0",
		"definition": "http://www.qudt.org/qudt/owl/1.0.0/quantity/Instances.html#AreaTemperature",
		"name": "Temperature",
		"Datastreams@iot.navigationLink": "http://gost.geodan.nl/v1.0/ObservedProperties(4200)/Datastreams"
	}
}

**Comment by bertt** [comment]
testcase: https://github.com/bertt/SensorThingsHCDT/blob/master/index.html

**Comment by bertt** [comment]
first part works: http://localhost:8080/v1.0/Datastreams(1)?$expand=ObservedProperty

**Comment by tebben** [comment]
http://localhost:8080/v1.0/Datastreams(1)?%24expand=ObservedProperty&%24select=unitOfMeasurement,ObservedProperty working now.

the expand query should use joins, will be picked up in https://github.com/Geodan/gost/issues/61

**Comment by bertt** [comment]
![dashboard](https://cloud.githubusercontent.com/assets/538812/20389755/9315efb6-accb-11e6-84ca-6c2f5ca959fa.png)
:clap:
