### ISSUE TITLE
Reorganize src code

### ISSUE THREAD

**Issue by bertt** [Geodan/gost#60]
Proposal: 

```
docker-compose.yml

. gost-db 

   Dockerfile (base image mdillon/postgis)

   create_gost_db.sql

. gost-dashboard 

   Dockerfile (base image nginx)
 
   nginx.conf

   index.html

     . css

     . js

     . viewers

. gost-service 

    Dockerfile (base image golang:latest)

    main.go

    config.yaml
```
    
Ports: 
. gost-dashboard: 8080
. gost-service: 8081
. gost-db: 5432

**Comment by tebben** [comment]
extra folder .gost-service means an extra addition in the go imports, making it too large for example: import (
  github.com/geodan/gost/src/gost-service/sensorthings/odata
)

Other proposal, moving docker files away from the gost source code to keep it clean:
- Move gost-dashboard to a separate repository (Tom's new Polymer dashboard?)
- .sql creation script to folder scripts
- Create docker folder in root or under scripts
          - machines
                - stable
                      - docker-compose.yml (using gost-service and gost-db images)
                      - readme.md
                - latest
                      - docker-compose.yml (building from source)
                      - readme.md
          - images
                - gost-service
                      - Dockerfile (base image golang:latest)
                      - readme.md
                - gost-db
                      - Dockerfile (base image mdillon/postgis)
                      - readme.md

**Comment by bertt** [comment]
other options:
. database code also in other repository
. remove 'src' from namespace, in my case the go code resides in D:\dev\go\src\github.com\geodan\gost\src with two times 'src' :-(

**Comment by bertt** [comment]
database stuff is moved to https://github.com/geodan/gost-db
dashboard stuff we'll move to https://github.com/geodan/gost-dashboard in later release

**Comment by bertt** [comment]
some tasks identified:

- move html/js code to new dashboard repository
- remove src directory from go code
- rename this repository to gost-server

**Comment by bertt** [comment]
html/js code is copied to new repository: https://github.com/gost/dashboard

**Comment by bertt** [comment]
html/js code for dashboard is removed from this repository

**Comment by bertt** [comment]
next task: remove src directory

**Comment by bertt** [comment]
- src folder is removed in https://github.com/Geodan/gost/pull/95

- docs are moved to https://github/com/gost/docs

- postman file is moved to https://github/com/gost/postman

- scripts moved to https://github/com/gost/scripts

**Comment by tebben** [comment]
Removed src folder in https://github.com/Geodan/gost/commit/9a4877defd6a5eafcd17a243d39b4e8bb7fe74b6
