### ISSUE TITLE
Get test suite level 3 running 

### ISSUE THREAD

**Issue by bertt** [Geodan/gost#64]
Test suite level 3 (filtering) thows an error on initialisation, something with HistoricalLocation

https://github.com/opengeospatial/ets-sta10/blob/master/src/main/java/org/opengis/cite/sta10/filteringExtension/Capability3Tests.java#L2164

**Comment by tebben** [comment]
After updating/patching a Location the test suite expects a newly created HistoricalLocation without removing the old linked one. The specs don't describe this behavior, first step is to figure out if the test is correct.

**Comment by tebben** [comment]
Test suite level 3 runs and passes "all" tests now. 1 test is changed locally on my setup since it contained an error, more info: https://github.com/opengeospatial/ets-sta10/issues/37
