### ISSUE TITLE
return null value instead of null string for optional properties

### ISSUE THREAD

**Issue by bertt** [Geodan/gost#68]
when posting a observation without optional ResultTime, the service returns "null" string, should be null value. Or omit the optional property in response when null.

maybe this accours also on other optional properties?

Sample:
Request:
http post to http://gost.geodan.nl/v1.0/Observations
{
  "phenomenonTime": "2016-05-09T11:04:15.790Z",
  "result" : 3800,
  "Datastream":{"@iot.id":18}
}
response:
{
   "@iot.id": 791422,
   "@iot.selfLink": "http://gost.geodan.nl/v1.0/Observations(791422)",
   "phenomenonTime": "2016-05-09T11:04:15.790Z",
   "result": 3800,
   **"resultTime": "null",**
   "Datastream@iot.navigationLink": "http://gost.geodan.nl/v1.0/Observations(791422)/Datastream",
   "FeatureOfInterest@iot.navigationLink": "http://gost.geodan.nl/v1.0/Observations(791422)/FeatureOfInterest"
}

**Comment by bertt** [comment]
https://github.com/Geodan/gost/blob/master/src/sensorthings/entities/observation.go#L69

**Comment by bertt** [comment]
we store the following:
"{"result": 38, "resultTime": "null", "phenomenonTime": "2015-04-12T22:00:00.000Z"}"

solution:
just do not store the resultTime when null (omitnull):
"{"result": 38, "phenomenonTime": "2015-04-12T22:00:00.000Z"}"

**Comment by bertt** [comment]
STA test gives error "Reading property "resultTime"of "OBSERVATION" fails."

so we have to return:
{"result": 38, resultTime: null, "phenomenonTime": "2015-04-12T22:00:00.000Z"}

so another solution is needed

**Comment by bertt** [comment]
option: change datatype Observation.ResultTime from string to *string?

**Comment by tebben** [comment]
returning null value instead if "null" for resultTime fixed in https://github.com/Geodan/gost/commit/3ab578b2564d9c0eee71d7c0260f6427c91a72b4

**Comment by bertt** [comment]
:thumbsup:
