### ISSUE TITLE
Q: How to POST Thing with HistoricalLocations?

### ISSUE THREAD

**Issue by justb4** [Geodan/gost#70]
I am using GOST v0.3 Docker version. I try to POST a `Thing` with a linked `Location`. I first POST the `Location` and use its `id` to use in payload of POST `Thing` (reason is to be easily PATCH when `Location` changed). This worked with the SensorUp STA. But with GOST I get an error *"Creating Historical Location went wrong"*. Here is the sequence of req/rsp:

```
2017-03-24 16:14:40,997 staoutput INFO POST Location - Payload: {
  "name": "71",
  "description": "Location of Station 71",
  "encodingType": "application/vnd.geo+json",
  "location": {
     "coordinates": [5.128898, 52.095246],
     "type": "Point"
  }
}
2017-03-24 16:14:41,002 httpoutput INFO Req nr 1 - response status: code=201 msg=Created

2017-03-24 16:14:41,003 httpoutput INFO Content: {
   "@iot.id": 13,
   "@iot.selfLink": "http://localhost:8080/v1.0/Locations(13)",
   "name": "71",
   "description": "Location of Station 71",
   "encodingType": "application/vnd.geo+json",
   "location": {
      "coordinates": [
         5.128898,
         52.095246
      ],
      "type": "Point"
   },
   "Things@iot.navigationLink": "http://localhost:8080/v1.0/Locations(13)/Things",
   "HistoricalLocations@iot.navigationLink": "http://localhost:8080/v1.0/Locations(13)/HistoricalLocations"
}
2017-03-24 16:14:41,003 staoutput INFO POST Thing - Payload: {
    "name": "71",
    "description": "Smart Emission station 71",
    "properties": {
      "id": "71"
    },
    "Locations": [
        {
          "@iot.id": 13
        }
    ]
}
2017-03-24 16:14:41,009 httpoutput INFO Req nr 2 - response status: code=400 msg=Bad Request
2017-03-24 16:14:41,009 httpoutput ERROR Headers: Access-Control-Allow-Origin: *
Content-Type: application/json; charset=UTF-8
Date: Fri, 24 Mar 2017 15:14:40 GMT
Content-Length: 215
2017-03-24 16:14:41,009 httpoutput INFO Content: {
   "error": {
      "status": "Bad Request",
      "code": 400,
      "message": [
         "Missing mandatory parameter: HistoricalLocation.time",
         "Creating Historical Location went wrong"
      ]
   }
}
```

I can't figure out where/how I should add  the `HistoricalLocations`, tried several ways, thought it was not mandatory. I also can't find an example like this:
http://www.sensorup.com/docs/?python#post-with-existing-location

The code is in https://github.com/Geonovum/smartemission/blob/master/etl/staoutput.py. It uses templates with parameter substitution for all POST requests like `Thing`: 
https://github.com/Geonovum/smartemission/blob/master/etl/statemplates/thing.json

**Comment by justb4** [comment]
Ok, got further and solved this question: using Docker GOST `latest`. Should include this [fix](https://github.com/Geodan/gost/commit/c020b6c7d8ff10bf4334171848b1f79a51df1f52#diff-c10ed38850decb8930ce3a3ac2539c45R46) creating `time` attr if missing. Now a `Thing` and `HistoricalLocation` is inserted when POSTing a `Thing` with linked `Location` as above! So can close this.

**Comment by tebben** [comment]
Correct, this issue is fixed in the latest build. Be aware that the docker latest image is an automatically build version including the latest commit so its not certain this image will run correctly. I planned the 0.4 release for next week.

**Comment by tebben** [comment]
By the way, during geobuzz you mentioned you would like to request Things based on a self assigned id, with the latest build you should be able to add an id to Thing.properties and request it something like this: http://host/v1.0/Things?$filter=properties.id eq myid

**Comment by justb4** [comment]
On 24-03-17 19:15, Tim Ebben wrote:
> By the way, during geobuzz you mentioned you would like to request
> Things based on a self assigned id, with the latest build you should be
> able to add an id to Thing.properties and request it something like
> this: http://host/v1.0/Things?$filter=properties.id eq myid
>
Ok, thanks, yes I already use the `properties.id` like in

```
       {
          "@iot.id": 18,
          "@iot.selfLink": "http://localhost:8080/v1.0/Things(18)",
          "name": "71",
          "description": "Smart Emission station 71",
          "properties": {
             "id": "71"
          },
          "Locations@iot.navigationLink": 
"http://localhost:8080/v1.0/Things(18)/Locations",
          "Datastreams@iot.navigationLink": 
"http://localhost:8080/v1.0/Things(18)/Datastreams",
          "HistoricalLocations@iot.navigationLink": 
"http://localhost:8080/v1.0/Things(18)/HistoricalLocations"
       },
```

I'll await 0.4.
