### ISSUE TITLE
Create Docker image for Raspberry Pi

### ISSUE THREAD

**Issue by bertt** [Geodan/gost#77]

**Comment by bertt** [comment]
proposal rpi images names: geodan/rpi-gost and geodan/rpi-gost-db ?
base image: resin/rpi-raspbian ?

**Comment by bertt** [comment]
postgis from https://store.docker.com/community/images/tobi312/rpi-postgresql-postgis ?

**Comment by tebben** [comment]
geodan/gost-rpi + geodan/gost-db-rpi more in line with naming of the repositories.
Base image: armhf/alpine

**Comment by bertt** [comment]
golang rpi image: https://store.docker.com/community/images/hypriot/rpi-golang (2.6K pulls) ?

**Comment by bertt** [comment]
i see both conventions used <name>-rpi and rpi-<name>

**Comment by bertt** [comment]
mosquitto rpi image: https://store.docker.com/community/images/pascaldevink/rpi-mosquitto (10K+ Pulls) ?

**Comment by bertt** [comment]
and we need a new docker-compose.yml file (rpi-docker-compose.yml ?)

**Comment by bertt** [comment]
tested some docker rpi images

- golang (hypriot/rpi-golang): Dockerfile created (https://github.com/Geodan/gost/blob/master/src/Dockerfile-rpi), must test it
- mqtt (pascaldevink/rpi-mosquitto): works allright
- postgis (tobi312/rpi-postgresql-postgis): Dockerfile created (https://github.com/Geodan/gost-db/blob/master/Dockerfile-rpi), issue with not running schema creation script https://github.com/Geodan/gost-db/issues/2 . Postgis looks ok.

**Comment by bertt** [comment]
getting there? https://store.docker.com/community/images/geodan/rpi-gost

**Comment by bertt** [comment]
updated db image, schema is now created https://store.docker.com/community/images/geodan/rpi-gost-db

**Comment by bertt** [comment]
added docker-compose-rpi.yml https://github.com/Geodan/gost/blob/master/src/docker-compose-rpi.yml

**Comment by bertt** [comment]
tested, works!

**Comment by bertt** [comment]
closing for now

**Comment by tebben** [comment]
Test GOST on RaspberryPi 2B - Raspbian Jessie Lite using the docker-compose-rpi

**Get Raspbian Jessie Lite**
  - Download and extract RASPBIAN JESSIE LITE (Version: March 2017 )from https://www.raspberrypi.org/downloads/raspbian/
  - Write image to sd card using "Win32 disk imager"

**Prepare RPI to access it remotely**
  - Insert SD card in RPI and connect it to a screen, power, internet and keyboard
  - Login using username = pi and password = raspberry
  - run: "sudo raspi-config" 
  - select: Interfacing Options -> SSH -> YES -> OK -> FINISH
  - run: "ifconfig"
  - write down IP
  - run: "sudo reboot"
  - disconnect keyboard and screen

**Install docker**
  - connect to RPI using putty 
  - login with same username and password as above
  - run: curl -sSL https://get.docker.com | sudo sh
	
**Install docker-compose**
  - run: sudo apt-get -y install python-pip
  - run: sudo pip install -U docker-compose
  - run: sudo chmod +x /usr/local/bin/docker-compose
	
**Get GOST up and running**
  - run: sudo mkdir dev
  - run: cd dev
  - run: sudo wget https://raw.githubusercontent.com/Geodan/gost/master/src/docker-compose-rpi.yml
  - run: sudo docker-compose -f docker-compose-rpi.yml -d up
  - grab a beer and wait for pulling images to complete
	
**Verify installation**
  - Browse to your-rpi-ip-here:8080 the dashboard should show up
  - Insert things, locations, datastreams, Sensors etc using the postman samples (318 ms)
  - Insert Observation (86 ms)
  - Check dashboard if inserted entities are there 
  - Open Datastreams -> 1 -> Observations -> Insert observation to Datastream 1 -> check if graph moves (if yes MQTT is running including websocket support)
