### ISSUE TITLE
Q: how to secure STA/MQTT API?

### ISSUE THREAD

**Issue by justb4** [Geodan/gost#78]
AFAIKS when running GOST with optional MQTT it seems that any client can issue modifying REST operations, e.g. create sensor, send observation. Is there a way in GOST to password-protect modification operations? For example that any client has read-access, but write-access is protected, for example via HTTP(S)-basic auth. Or is it the intention to handle secured access in the frontend-webserver (Nginx, Apache2) level? Thanks for any suggestions.

**Comment by bertt** [comment]
see 7.7 'SensorThings API and Security' in the Specs: "SensorThings API does not define specific security capabilities"

**Comment by bertt** [comment]
http://docs.opengeospatial.org/is/15-078r6/15-078r6.html#21

**Comment by justb4** [comment]
Ok, thanks for quick reply, we'll proceed from there!

**Comment by justb4** [comment]
Tip: GOST (or any STA) can be secured at the  HTTP-proxy, e.g. Apache2 or nginx, for example to require basic authentication for modifying requests with Apache2 (our usernames are different):

```
	<Location /gost/v1.0/>
		<Limit POST PUT DELETE PATCH>
			AuthType Basic
			AuthName "GOST Writer"
			AuthUserFile "/etc/apache2/thepwfile"
			Require user gost
		</Limit>
	</Location>
```

And to secure the Dashboard (also secures modifying operations within Dashboard):

```
	<Location "/gost/Dashboard/">
		AuthType Basic
		AuthName "GOST Writer"
		AuthUserFile "/etc/apache2/thepwfile"
		Require user gost
	</Location>
```

**Comment by bertt** [comment]
thanks, I've put this information here: https://github.com/Geodan/gost/blob/master/docs/gost_security.md

**Comment by justb4** [comment]
great!
