### ISSUE TITLE
Base URL issue with HTTP-proxied Dashboard

### ISSUE THREAD

**Issue by justb4** [Geodan/gost#80]
Running standard GOST 0.4 with Docker.

We have a setup where GOST runs via an Apache2 HTTP-proxy. This works fine for the STA API URL, but the Dashboard gave JS-errors since the URL to the STA API is not mapped properly.

I think the STA API works as it is mapped to the GOST-config property ``gost_server_external_uri`` 
(via an  env-property on `docker run`). But the Dashboard uses a base URL via a util function ``getUrl()`` in [app.js](https://github.com/Geodan/gost/blob/master/src/client/js/app.js) which returns `window.location.origin`, not the path to the proxied URL. 

So for example, when the external/proxied URL is `http://myserver/gost` the Dashboard would attempt calls to `http://myserver/v1.0/Things` and `http://myserver/Dashboard` etc i.s.o.  `http://myserver/gost/v1.0/Things` and `http://myserver/gost/Dashboard/`. 

I fixed this locally by rewriting `getUrl()` i.s.o. returning `window.location.origin` to use the `pathname` and stripping off the `/Dashboard/`-part as follows:

```
function getUrl() {
    // Need pathname minus /Dashboard/
    var path = window.location.pathname;
    path = path.substring(0, path.lastIndexOf('/Dashboard'));
    return window.location.origin + path;
}
```

This works for us, but probably better to use the ``gost_server_external_uri`` somehow within the JS-client.

**Comment by bertt** [comment]
ok thanks. Note: The gost_server_external_uri environment variable is used server-side for setting absolute hypermedia urls in the HTTP responses (for running GOST behind proxy scenario)

**Comment by justb4** [comment]
Ok, will you apply my or other fix for the Dashboard? I think in cases the external URI can be determined from proxy HTTP headers `X-Forwarded-Server`.

**Comment by bertt** [comment]
. created new issue for http header X-Forwarded-Server: https://github.com/Geodan/gost/issues/83
. code looks ok, shall test it first

**Comment by bertt** [comment]
code change is in https://github.com/Geodan/gost/commit/b5dd25df34f733ff2e2956f4b4c968c4756a83af

**Comment by justb4** [comment]
Pulled in latest Docker image, but still see a redirect (301) to base URL without `/gost` in path. But I think I also found something. e.g. this still redirects with 404:

```
nusa:~ just$ wget 'http://test.smartemission.nl/gost/v1.0/Things/?$top=20&$skip=20'
--2017-04-13 12:08:14--  http://test.smartemission.nl/gost/v1.0/Things/?$top=20&$skip=20
Resolving test.smartemission.nl... 89.31.100.234
Connecting to test.smartemission.nl|89.31.100.234|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /v1.0/things?$top=20&$skip=20 [following]
--2017-04-13 12:08:14--  http://test.smartemission.nl/v1.0/things?$top=20&$skip=20
Reusing existing connection to test.smartemission.nl:80.
HTTP request sent, awaiting response... 404 Not Found
2017-04-13 12:08:14 ERROR 404: Not Found.
```

But removing the trailing `/` so `Things?` i.s.o. `Things/?' (latter is in 'next page' URL), it resolved ok:


```
nusa:~ just$ wget 'http://test.smartemission.nl/gost/v1.0/Things?$top=20&$skip=20'
--2017-04-13 12:08:29--  http://test.smartemission.nl/gost/v1.0/Things?$top=20&$skip=20
Resolving test.smartemission.nl... 89.31.100.234
Connecting to test.smartemission.nl|89.31.100.234|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/json]
Saving to: ‘Things..                                                                                           ]  11.54K  --.-KB/s    in 
```

So maybe the fix is as simple as to not include the trailing '/' in the next page URLs (or handle `/?` as is AFAIK valid URL). For completeness my proxy setting is (with the host `gost` linked via Docker):

```
	<Location /gost>
	   ProxyPreserveHost On
	   ProxyPass http://gost:8080
	   ProxyPassReverse http://gost:8080
```

**Comment by bertt** [comment]
just checking: is this correct issue? or about https://github.com/Geodan/gost/issues/82

**Comment by justb4** [comment]
Put my (crossing) comment in wrong issue here, moved it to #82.
