### ISSUE TITLE
External GOST server URI is not used for iot.nextLink

### ISSUE THREAD

**Issue by justb4** [Geodan/gost#82]
We have GOST running via an HTTP proxy with an external link set via -e gost_server_external_uri=http://test.smartemission.nl/gost/ in `docker run`. This works fine for all `iot.navigationLinks` but not for `iot.nextLink` used when paging via the browser. Best explained via image below:

![gost-nextlink](https://cloud.githubusercontent.com/assets/582630/24913410/6beee80c-1ed1-11e7-8384-947687866849.jpg)

Here `iot.nextLink` should point to http://test.smartemission.nl/gost/v1.0/things/?$top=20&$skip=20 i.s.o. http://test.smartemission.nl/v1.0/things/?$top=20&$skip=20

**Comment by tebben** [comment]
Get handler used the incoming host + path instead of the externalURI.  nextLink is now based on config ExternalURI (http://test.smartemission.nl/gost/) + incoming Url.Path (/v1.0/things/)

**Comment by justb4** [comment]
Thanks for quick action! Using Docker latest I now see:

```
@iot.nextLink: "http://test.smartemission.nl/gost/v1.0/Things/?$top=20&$skip=20",
```
But somehow this link redirects to http://test.smartemission.nl/v1.0/things?$top=20&$skip=20, not to the external URI, e.g. 

```
root@SETEST:~# wget 'http://test.smartemission.nl/gost/v1.0/Things/?$top=20&$skip=20'
--2017-04-11 17:23:19--  http://test.smartemission.nl/gost/v1.0/Things/?$top=20&$skip=20
Resolving test.smartemission.nl (test.smartemission.nl)... 89.31.100.234
Connecting to test.smartemission.nl (test.smartemission.nl)|89.31.100.234|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /v1.0/things?$top=20&$skip=20 [following]
--2017-04-11 17:23:19--  http://test.smartemission.nl/v1.0/things?$top=20&$skip=20
Reusing existing connection to test.smartemission.nl:80.
HTTP request sent, awaiting response... 404 Not Found
2017-04-11 17:23:19 ERROR 404: Not Found.
```

**Comment by tebben** [comment]
Investigating the problem and trying to create a fix

**Comment by tebben** [comment]
StrictSlash is set to false now which prevents the HTTP server from redirecting, changed the nextlink to remove the trailing / 

301 should not occur anymore, can you check if it works for you with the latest version?

**Comment by justb4** [comment]
Pulled in latest Docker image, but still see a redirect (301) to base URL without `/gost` in path. But I think I also found something. e.g. this still redirects with 404:

```
nusa:~ just$ wget 'http://test.smartemission.nl/gost/v1.0/Things/?$top=20&$skip=20'
--2017-04-13 12:08:14--  http://test.smartemission.nl/gost/v1.0/Things/?$top=20&$skip=20
Resolving test.smartemission.nl... 89.31.100.234
Connecting to test.smartemission.nl|89.31.100.234|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /v1.0/things?$top=20&$skip=20 [following]
--2017-04-13 12:08:14--  http://test.smartemission.nl/v1.0/things?$top=20&$skip=20
Reusing existing connection to test.smartemission.nl:80.
HTTP request sent, awaiting response... 404 Not Found
2017-04-13 12:08:14 ERROR 404: Not Found.
```

But removing the trailing `/` so `Things?` i.s.o. `Things/?' (latter is in 'next page' URL), it resolved ok:


```
nusa:~ just$ wget 'http://test.smartemission.nl/gost/v1.0/Things?$top=20&$skip=20'
--2017-04-13 12:08:29--  http://test.smartemission.nl/gost/v1.0/Things?$top=20&$skip=20
Resolving test.smartemission.nl... 89.31.100.234
Connecting to test.smartemission.nl|89.31.100.234|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/json]
Saving to: ‘Things..                                                                                           ]  11.54K  --.-KB/s    in 
```

So maybe the fix is as simple as to not include the trailing '/' in the next page URLs (or handle `/?` as is AFAIK valid URL). For completeness my proxy setting is (with the host `gost` linked via Docker):

```
	<Location /gost>
	   ProxyPreserveHost On
	   ProxyPass http://gost:8080
	   ProxyPassReverse http://gost:8080
```

**Comment by tebben** [comment]
The docker latest build was from 2 hours ago and auto-build failed afterwards because of a missing go get in the dockerfile. This is fixed now and docker image gost:latest is updated with the latest commits.

**Comment by justb4** [comment]
Yes, works with latest Docker! Thanks.

One more thing: is the Dashboard also supposed to show "next-pages"? I never saw them using a proxy setup (can't remember if they showed without). See e.g. image (we have about few thousand observations). 

![gost-dashboard-nonext](https://cloud.githubusercontent.com/assets/582630/25007540/23c1e188-2061-11e7-9263-d049bda112cd.jpg)

**Comment by bertt** [comment]
No next page buttons are not there (yet), we welcome pr's -:)

**Comment by bertt** [comment]
Closing because issue fixed
