### ISSUE TITLE
Dependency management with Glide

### ISSUE THREAD

**Issue by bertt** [Geodan/gost#86]
See branch glide_experiment (https://github.com/Geodan/gost/tree/glide_experiment) for experiment with Glide (https://github.com/Masterminds/glide) for dependency management.

How it works:
- glide is a command line tool, needs to be installed
- glide create: creates glide.yaml file with version numbers (using a wizzard) (https://github.com/Geodan/gost/blob/glide_experiment/glide.yaml)
- glide install: installs dependencies in the project 'vendor' folder (which is in gitignore now)

Consequences:
- Every developer shall use Glide (otherwise developers can use use different versions of dependencies)

Todo:
- Fix Docker files with installing/using Glide
- Check unit tests

Question: Shall we use Glide in GOST?

**Comment by bertt** [comment]
Note: Number of packages with version numbers is quite low:  github.com/eclipse/paho.mqtt.golang, github.com/gorilla/mux and for tests github.com/stretchr/testify

**Comment by tebben** [comment]
An option is to fork all the used packages to gost organisation and create version numbers ourselfs

**Comment by bertt** [comment]
So we have now 4 options:

- do nothing
- use glide
- use go-dept
- fork dependencies

Whats the recommended way to do dependency management in Golang?

**Comment by bertt** [comment]
for now we don't use package manager. risk taken: GOST breaking on dependency update with breaking changes

**Comment by tebben** [comment]
Looks like dep is going to be the official dependency management tool for go: [github.com/golang/dep](https://github.com/golang/dep) - [Roadmap](https://github.com/golang/dep/wiki/Roadmap)

I suggest we wait for a stable version
