### ISSUE TITLE
STA test 3 issues

### ISSUE THREAD

**Issue by bertt** [Geodan/gost#89]
When running STA test 3 I see 2 failing tests:

- checkQueriesPriorityOrdering

- readEntitiesWithFilterQO

Can we fix these tests?

**Comment by bertt** [comment]
Test readEntitiesWithFilterQO is discussed here: https://github.com/opengeospatial/ets-sta10/issues/37

**Comment by bertt** [comment]
Description test checkQueriesPriorityOrdering:

Request:  http://localhost:8080/v1.0/Observations?$count=true&$top=1&$skip=2&$orderby=phenomenonTime%20asc&$filter=result%20gt%20'3'

Response: 
{
   "@iot.count": 9,
   "@iot.nextLink": "http://localhost:8080/v1.0/Observations?$filter=result gt '3'&$count=true&$orderby=phenomenonTime asc&$top=1&$skip=3",
   "value": [
      {
         "@iot.id": 30,
         "@iot.selfLink": "http://localhost:8080/v1.0/Observations(30)",
         "phenomenonTime": "2015-03-06T00:00:00.000Z",
         "result": 6,
         "Datastream@iot.navigationLink": "http://localhost:8080/v1.0/Observations(30)/Datastream",
         "FeatureOfInterest@iot.navigationLink": "http://localhost:8080/v1.0/Observations(30)/FeatureOfInterest",
         "resultTime": null
      }
   ]
}

Test result:
The query order of execution is not correct. The expected count is 6, but the service returned 9 expected [6] but found [9]
Expected :6
Actual   :9

**Comment by tebben** [comment]
12 observations are posted with the following result values: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12
Query asks for observations where the result is > 3 = 4, 5, 6, 7, 8, 9, 10, 11, 12 = 9 returned observations. The test is not expected observations with result 10, 11, 12 becaus of bad comparison on strings

**Comment by bertt** [comment]
is there an issue on the ets-sta site about this? Or is it the same as opengeospatial/ets-sta10#37

**Comment by bertt** [comment]
so for my undertstanding the issue is as follows:

- database has 12 obervations with values 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12
- query asks for observations > '3' 
- expected result according to test: 6 observations (with values 4,5,6,7,8,9)
- actual result: 9 obervations (with values 4, 5, 6, 7, 8, 9, 10, 11,12)

**Comment by tebben** [comment]
yes

**Comment by bertt** [comment]
analysis:

. in the GOST code the query string ('3') is converted to int (3) and then the query is performed,
resulting in 9 observations (method int compare)

possible fix: do not convert the query string from '3' to 3, but convert the observation results to string, resulting in 6 observations (method string compare). 

Is this possible to do? What are the consequences?

**Comment by tebben** [comment]
It is possible but result values are inserted as integers, I'm not going to change the code to get faulty tests working.

**Comment by bertt** [comment]
Proposal:
- Check if there is type mismatch between type of request and type in database 
- if typemismatch == true: Execute query (where part) with request as-is (no conversion) and observations.result converted to the requested type (string in the case of the test)
- if typemismatch == false: Just do the query as normal (no conversions)
- In the response we always send the observation.results back in the same type as inserted (ints in the case of the test) - so no type conversion needed here

**Comment by bertt** [comment]
Count query: 
SELECT COUNT(*) FROM v1.observation WHERE observation.data -> 'result' > '3'
Actual result: 9
Expected result: 6

**Comment by bertt** [comment]
Solution: change query
SELECT * FROM v1.observation WHERE observation.data ->> 'result' > '3'
Actual result: 6

**Comment by tebben** [comment]
Added a workaround for now.
When filtering on observation.result with a string as input the observation.result will be fetched as string and compared
